version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    networks:
      - kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "TOPIC_AUDIT_LOG:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    links: # 连接本compose文件创建的container
      - kafka
    networks:
      - kafka
    environment:
      - ZK_HOSTS=zookeeper:2181
networks:
  kafka: